### ISSUE TITLE
stream results?

### ISSUE THREAD

**Issue by ralphtheninja** [doowb/module-dependents#1]
:wave: 

Great module!

Is there a simple way of streaming the data (e.g. `.pipe()`) as it comes rather than waiting for the promise to resolve?

Cheers

**Comment by ralphtheninja** [comment]
@doowb If there's anything that needs to be coded I can def help out.

**Comment by doowb** [comment]
Not directly in this module but it's something that I've wanted to do.

Help would be great! I'll put together some issues and ping you on them later tonight or tomorrow morning. I think it'll involve changes in one or two dependencies

**Comment by ralphtheninja** [comment]
I'm thinking the streaming thing could be used by this module.

**Comment by doowb** [comment]
> I'm thinking the streaming thing could be used by this module.

@ralphtheninja I was thinking the same thing! This will also lead the way for a better interface in [dependents-cli](https://github.com/doowb/dependents-cli)

I created issues in the [npm-api](https://github.com/doowb/npm-api/issues) and [npm-api-dependents](https://github.com/doowb/npm-api-dependents/issues) repositories.

The `npm-api` issues are more of an internal refactor and not necessary to get streaming working in this module. The `npm-api-dependents` issue is a refactor of the code to enable streaming in this module. The main goal is to remove the generator/promise code and use a streaming interface.

**Comment by ralphtheninja** [comment]
Stream support implemented in https://github.com/doowb/npm-api-dependents/pull/2

**Comment by doowb** [comment]
@ralphtheninja I updated this module and published 1.0.0 with the changes from `npm-api-dependents`.
